import os
import yaml
import re
import sys
import io
if sys.stdout.encoding and sys.stdout.encoding.lower() not in ("utf-8", "utf-8-sig"):
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
from pathlib import Path

# Dynamic path resolution
SCRIPT_DIR = Path(__file__).parent
WIKI_ROOT = SCRIPT_DIR.parent.parent
WIKI_DIR = WIKI_ROOT / "03_wiki"
INDEX_DIR = WIKI_ROOT / "01_schema" / "index"
MASTER_INDEX = WIKI_ROOT / "01_schema" / "index.md"

if not INDEX_DIR.exists():
    INDEX_DIR.mkdir(parents=True, exist_ok=True)

# Create index subdirectory
INDEX_SUBDIR = INDEX_DIR
if not INDEX_SUBDIR.exists():
    INDEX_SUBDIR.mkdir(parents=True, exist_ok=True)

def extract_frontmatter(content):
    match = re.search(r'^---\s*\n(.*?)\n---\s*\n', content, re.DOTALL)
    if match:
        return match.group(1)
    return None

def get_node_info(path):
    with open(path, "r", encoding="utf-8", errors="ignore") as f:
        content = f.read()
    
    fm_text = extract_frontmatter(content)
    node_name = os.path.splitext(os.path.basename(path))[0]
    
    thesis = ""
    if fm_text:
        try:
            data = yaml.safe_load(fm_text)
            thesis = data.get('thesis', "")
            if isinstance(thesis, str):
                thesis = thesis.strip().replace('\n', ' ')
            else:
                thesis = str(thesis)
        except:
            # Simple regex fallback
            match = re.search(r'thesis:\s*(.*)', fm_text, re.MULTILINE | re.DOTALL)
            if match:
                thesis = match.group(1).strip().strip('"').strip("'")
    
    return node_name, thesis

def main():
    preferred_order = [
        'mechanisms', 'definitions', 'relationships', 'concepts',
        'conventions', 'evidence', 'perspectives', 'contradictions',
        'syntheses', 'domains', 'glossary',
    ]
    existing_dirs = [d.name for d in WIKI_DIR.iterdir() if d.is_dir() and not d.name.startswith(".")]
    extras = sorted(d for d in existing_dirs if d not in preferred_order)
    subdirs = [d for d in preferred_order if d in existing_dirs] + extras
    master_index = []

    for subdir in subdirs:
        dir_path = WIKI_DIR / subdir
        if not dir_path.exists():
            continue
            
        nodes = []
        for file in dir_path.glob("*.md"):
            if file.name == ".gitkeep" or file.name.startswith("_"):
                continue
            name, thesis = get_node_info(file)
            nodes.append((name, thesis))
        
        if nodes:
            nodes.sort(key=lambda x: x[0].lower())
            
            # Write to type-specific index
            type_file = f"index_{subdir.lower()}.md"
            type_path = INDEX_SUBDIR / type_file
            with open(type_path, "w", encoding="utf-8") as f:
                f.write(f"# WIKI INDEX: {subdir.capitalize()}\n\n")
                for name, thesis in nodes:
                    f.write(f"- [[{name}]] — **Thesis:** {thesis}\n")
            
            master_index.append((subdir, type_file, len(nodes)))

    # Write Master Index
    with open(MASTER_INDEX, "w", encoding="utf-8") as f:
        f.write("# LLM WIKI MASTER INDEX (v4.0)\n\n")
        f.write("Knowledge infrastructure refactored for atomic retrieval and scalability.\n\n")
        f.write("| Category | Sub-Index | Node Count |\n")
        f.write("| :--- | :--- | :--- |\n")
        for category, file_name, count in master_index:
            f.write(f"| {category.capitalize()} | [Link](index/{file_name}) | {count} |\n")

    print(f"Refactored index.md into {len(master_index)} sub-indexes.")

    # Thêm _index.md trực tiếp trong mỗi thư mục wiki category
    _write_dir_indexes(master_index)
    print(f"Written _index.md into {len(master_index)} wiki category directories.")


def _write_dir_indexes(master_index):
    """Ghi _index.md vào từng thư mục 03_wiki/<category>/ để navigation nhanh."""
    for subdir, _, _ in master_index:
        dir_path = WIKI_DIR / subdir
        if not dir_path.exists():
            continue

        nodes = []
        for file in sorted(dir_path.glob("*.md")):
            if file.name.startswith("_") or file.name == ".gitkeep":
                continue
            name, thesis = get_node_info(file)
            nodes.append((name, thesis))

        if not nodes:
            continue

        idx_path = dir_path / "_index.md"
        with open(idx_path, "w", encoding="utf-8") as f:
            f.write(f"# INDEX: {subdir.capitalize()} ({len(nodes)} nodes)\n")
            f.write(f"> Auto-generated by gen_index.py — do not edit manually.\n\n")
            for name, thesis in nodes:
                short = (thesis[:90] + "...") if len(thesis) > 90 else thesis
                f.write(f"- [[{name}]] — {short}\n")


if __name__ == "__main__":
    main()

